// Canonical US Layer 1 intake schema.
//
// This is a verbatim port of the `usState` default-value literal from
// layer1_us.html:4069-4381 (the vanilla-JS wizard). That file is the real
// schema source of truth for this product: dag_py's node definitions cite
// these exact dotted field paths in their own `layer1_fields` tuples (e.g.
// ustax.py's `"amt_inputs.minimum_tax_credit_carryforward_usd"`), and
// lib/dag-adapter.js reads the serialized result of this shape back out of
// localStorage under the same key every existing compute path already uses.
//
// Deliberately NOT reconciled against layer1_us.html's second, separate
// SUPERSET_SCHEMA_TEMPLATE object (~1,450 lines, used there only to
// guarantee a stable export shape via a deep-merge). That reconciliation
// is flagged as a known follow-up, not attempted here — see the migration
// gap report.

export function createDefaultUsState() {
  return {
    profile: {
      tax_entity_type: "individual",
      llc_tax_election: "individual",
      incorporation_state: null,
      incorporated_in_us: null,
      full_name: null,
      date_of_birth: null,
      filing_status: "single",
      ssn_or_itin: null,
      ssn_or_itin_type: "none",
      dependents_count: 0,
      spouse_is_us_person: null,
      trump_accounts_opened: false,
      trump_accounts_children: [],
      trump_accounts_num_children: 0,
      trump_accounts_children_born_2025_2028: 0,
      trump_accounts_total_contributions_usd: 0,
      trust_retained_income_usd: 0,
    },
    corporate_profile: {
      entity_name: null,
      ein: null,
      date_of_incorporation: null,
      state_of_domicile: null,
      naics_code: null,
      fiscal_year_end: "12-31",
      is_foreign_owned_25_pct: false,
      is_foreign_corporation: false,
    },
    corporate_international: {
      fdii_eligible_income: null,
      ncti_tested_income: null,
      form_5472_related_parties: [],
    },
    corporate_financials: {
      schedule_l: {
        assets_beginning: 0,
        assets_ending: 0,
        liabilities_beginning: 0,
        liabilities_ending: 0,
        equity_beginning: 0,
        equity_ending: 0,
      },
      schedule_m1: {
        net_income_per_books: 0,
        federal_tax_expense: 0,
        meals_disallowed_50: 0,
        tax_depreciation_over_book: 0,
        taxable_income: 0,
      },
      schedule_m2: {
        retained_earnings_beginning: 0,
        distributions_dividends_paid: 0,
        retained_earnings_ending: 0,
      },
    },
    us_residency_detail: {
      is_us_citizen: false,
      has_green_card: false,
      green_card_grant_date: null,
      i407_surrendered_date: null,
      green_card_years_held: 0,
      expatriation_net_worth_usd: 0,
      expatriation_avg_net_income_tax_usd: 0,
      form_8854_5yr_compliance_certified: false,
      us_days_current_year: 0,
      us_days_minus_1_year: 0,
      us_days_minus_2_years: 0,
      exempt_individual_status: "none",
      exempt_first_year: null,
      exempt_prior_years_count: 0,
      exempt_student_closer_conn_exception: false,
      exempt_scholar_lookback_exception: false,
      closer_connection_claim: null,
      first_year_choice_election: false,
      first_year_choice_entry_date: null,
      s6013g_joint_election: false,
      spt_day_count_weighted: 0,
      spt_test_met: false,
      final_us_residency_status: "NON_RESIDENT_ALIEN",
      dtaa_treaty_residence: "none",
      residency_start_date: null,
      residency_end_date: null,
    },
    corp_state_nexus: {
      physical_states: [],
      economic_states: [],
      needs_apportionment: false,
      apportionment_factors: {},
      has_remote_workers: false,
    },
    state_residency: {
      jan_1_domicile_state: "",
      dec_31_domicile_state: "",
      total_states_footprint: [],
      primary_state_of_residence: "",
      moved_states_this_year: false,
      previous_state: "",
      move_date: null,
      state_days_in_current_state: null,
      dependents_school_state: "",
      primary_bank_and_medical_nexus_state: "",
      vehicles_registered_state: "",
      active_duty_military_or_spouse: false,
      military_home_state_of_record: "",
      military_duty_station_state: "",
      ca_planning_departure: false,
      ca_retains_property_or_voter_reg: false,
    },
    income_us_source: {
      has_employment_income: false,
      has_capital_gains: false,
      has_crypto: false,
      stocks_needs_wash_sale_reconciliation: false,
      crypto_needs_wash_sale: false,
      has_sec_1256: false,
      has_qof_rollover: false,
      has_qsbs: false,
      has_real_estate: false,
      has_1031_exchange: false,
      has_installment_sale: false,
      has_collectibles: false,
      has_capital_loss_carryovers: false,
      st_loss_carryover_usd: null,
      lt_loss_carryover_usd: null,
      self_employment: [],
      partnerships_k1: [],
      s_corporations_k1: [],
      c_corporations_1120: [],
      farming_schedule_f: [],
      trusts_estates_k1: [],
      se_health_insurance_deduction_usd: null,
      se_retirement_deduction_usd: null,
      interest_us_bank_usd: null,
      interest_us_treasury_usd: null,
      interest_us_oid_usd: null,
      interest_us_private_usd: null,
      interest_us_exempt_usd: null,
      interest_us_source_usd: null,
      ordinary_dividends_us_source_usd: null,
      qualified_dividends_us_source_usd: null,
      stcg_us_source_usd: null,
      ltcg_us_source_usd: null,
      rental_income_us_source_usd: null,
      royalty_income_us_source_usd: null,
      k1_passthrough_income_usd: null,
      ira_distributions_usd: null,
      "401k_distributions_usd": null,
      social_security_benefits_usd: null,
      crypto_transactions: [],
    },
    income_foreign_source: {
      foreign_wages: [],
      foreign_interest_usd: null,
      foreign_dividends_usd: null,
      foreign_stcg_usd: null,
      foreign_ltcg_usd: null,
      foreign_rental_income_usd: null,
      foreign_pension_income_usd: null,
      section_988_gains_losses: [],
    },
    foreign_tax_credit_other: {
      entries: [],
    },
    equity_compensation: {
      has_equity_comp: false,
      iso_exercises: [],
      nso_exercises: [],
      rsu_vestings: [],
      espp_purchases: [],
      unvested_restricted_stock_awards: [],
    },
    foreign_earned_income: {
      claims_feie: false,
      qualification_test: "physical_presence",
      tax_home_country: "",
      physical_presence_start_date: null,
      physical_presence_end_date: null,
      days_in_us_during_test_period: 0,
      us_business_days: 0,
      bona_fide_residence_start_date: null,
      foreign_earned_income_usd: null,
      feie_amount_claimed_usd: 0,
      foreign_housing_expenses_usd: null,
      housing_exclusion_base_usd: 21264,
      housing_exclusion_cap_usd: 39870,
      foreign_housing_exclusion_usd: 0,
    },
    bank_accounts: [],
    fbar_aggregate_peak_usd: 0,
    form_8938_required: false,
    financial_holdings: [],
    real_estate: {
      has_real_estate_transaction: false,
      properties: [],
    },
    retirement_accounts: {
      traditional_ira_contribution_usd: null,
      roth_ira_contribution_usd: null,
      backdoor_roth_executed: false,
      "401k_employee_contribution_usd": null,
      "401k_employer_match_usd": null,
      roth_401k_contribution_usd: null,
      hsa_contribution_usd: null,
      hsa_coverage_type: null,
      solo_401k_contribution_usd: null,
      sep_ira_contribution_usd: null,
      rmd_required: false,
      rmd_amount_usd: 0,
      indian_epf_balance_usd: null,
      indian_ppf_balance_usd: null,
      indian_nps_balance_usd: null,
    },
    foreign_entities: {
      owns_10_percent_foreign_corp: false,
      foreign_corporations: [],
      owns_10_percent_foreign_partnership: false,
      foreign_partnerships: [],
      owns_foreign_disregarded_entity: false,
      foreign_de_details: [],
    },
    foreign_gifts_and_trusts: {
      received_foreign_gifts_above_100k: false,
      foreign_gifts: [],
      is_us_beneficiary_of_foreign_trust: false,
      foreign_trust_details: [],
      received_gift_from_covered_expatriate: false,
    },
    itemized_deductions_and_credits: {
      use_standard_or_itemized: "auto",
      state_and_local_taxes_paid_usd: null,
      mortgage_interest_paid_usd: null,
      mortgage_acquisition_date: null,
      charitable_contributions_cash_usd: null,
      charitable_contributions_appreciated_usd: null,
      medical_expenses_usd: null,
      casualty_loss_federal_disaster_usd: null,
      hsa_contributions_usd: null,
      student_loan_interest_usd: null,
      educator_expenses_usd: null,
      child_tax_credit_dependents: null,
      credit_for_other_dependents: null,
      child_and_dependent_care_expenses_usd: null,
      education_credits_aotc_usd: null,
      education_credits_llc_usd: null,
      saver_credit_eligible: false,
      funded_529_plan: false,
      "529_contributions_usd": null,
      "529_state_deduction_state": "",
      qbi_deduction_eligible: false,
      qbi_deduction_usd: 0,
    },
    amt_inputs: {
      iso_preference_total_usd: 0,
      salt_addback_usd: 0,
      private_activity_bond_interest_usd: null,
      amt_exemption_usd: 0,
      amti_usd: 0,
      tentative_minimum_tax_usd: 0,
      amt_due_usd: 0,
      minimum_tax_credit_carryforward_usd: null,
    },
    niit_inputs: {
      modified_agi_usd: 0,
      niit_threshold_usd: 200000,
      net_investment_income_usd: 0,
      niit_due_usd: 0,
    },
    ftc_inputs: {
      claims_ftc: false,
      claims_ftc_simplified_under_300: false,
      elect_accrued_method: false,
      prior_year_carryovers_usd: 0,
      ftc_baskets: [],
    },
    withholding_and_estimated: {
      federal_withholding_total_usd: 0,
      state_withholding_total_usd: 0,
      estimated_tax_q1_apr15_usd: null,
      estimated_tax_q2_jun15_usd: null,
      estimated_tax_q3_sep15_usd: null,
      estimated_tax_q4_jan15_usd: null,
      prior_year_total_tax_usd: null,
      additional_medicare_tax_owed_usd: 0,
    },
    nra_specific: {
      files_form_1040nr: false,
      s6013h_joint_election: false,
      w8ben_aggregate_status: "none",
      form_w7_itin_application_filed: false,
      us_eci_income_usd: 0,
      us_fdap_income_usd: 0,
      treaty_rate_claims: [],
      us_real_property_disposed: false,
      firpta_withholding_usd: null,
      is_lrs_investor: false,
    },
    metadata: {
      us_calendar_year: 2026,
      request_id:
        typeof crypto !== "undefined" && crypto.randomUUID
          ? crypto.randomUUID()
          : "us-l1-" + Date.now(),
      source: "onboarding",
      input_completeness: "provisional",
      schema_version: "layer1_us_v1",
      obbba_threshold_table_version: "rev_proc_2025_32",
      created_at: new Date().toISOString(),
      last_updated_at: new Date().toISOString(),
      intake_completed: false,
    },
  };
}

// The 22 real wizard steps (layer1_us.html's `stepIds`, layer1_us.html:5888,
// minus the vestigial 'step-k1' entry that has no matching panel/button
// anywhere in the source file — dropped here as dead-reference cleanup).
export const STEP_IDS = [
  "step-onboarding",
  "step-profile",
  "step-income-us",
  "step-income-foreign",
  "step-business",
  "step-capgains",
  "step-real-estate",
  "step-passive",
  "step-retirement",
  "step-equity",
  "step-deductions",
  "step-feie",
  "step-ftc",
  "step-amt-niit",
  "step-nra",
  "step-state",
  "step-entities",
  "step-gifts",
  "step-withholding",
  "step-banks",
  "step-bank-sync",
  "step-output",
];

export const STEP_LABELS = {
  "step-onboarding": "Onboarding",
  "step-profile": "Profile & Residency",
  "step-income-us": "US-Source Income",
  "step-income-foreign": "Foreign-Source Income",
  "step-business": "Business & Entities Income",
  "step-capgains": "Capital Gains",
  "step-real-estate": "Real Estate",
  "step-passive": "Passive Income",
  "step-retirement": "Retirement Accounts",
  "step-equity": "Equity Compensation",
  "step-deductions": "Deductions & Credits",
  "step-feie": "Foreign Earned Income Exclusion",
  "step-ftc": "Foreign Tax Credit",
  "step-amt-niit": "AMT & NIIT",
  "step-nra": "NRA / 1040-NR",
  "step-state": "State Residency & Tax",
  "step-entities": "Foreign Entities",
  "step-gifts": "Foreign Gifts & Trusts",
  "step-withholding": "Withholding & Estimated Tax",
  "step-banks": "Foreign Bank Accounts (FBAR)",
  "step-bank-sync": "Bank Sync",
  "step-output": "Review & Export",
};
