// Embed brand fonts (latin subset) as base64 @font-face so they work with ZERO
// external requests — required for offline file:// (assetPrefix "." breaks
// @fontsource's relative url()s). Regenerable; run at prebuild.
//   Manrope            — UI/body text
//   Cormorant Garamond — the WISING wordmark specifically (confirmed via the
//                         site's own computed font-family in devtools)
const fs = require("fs");
const path = require("path");
const base = path.resolve(__dirname, "..", "node_modules", "@fontsource");
const out = path.resolve(__dirname, "..", "app", "fonts-embedded.css");

const FONTS = [
  { family: "Manrope", slug: "manrope", weights: [400, 500, 600, 700, 800] },
  { family: "Cormorant Garamond", slug: "cormorant-garamond", weights: [500, 600, 700] }
];

let css = "/* Auto-generated by scripts/embed-font.js — base64, do not edit. */\n";
let count = 0;
FONTS.forEach(({ family, slug, weights }) => {
  weights.forEach((w) => {
    const f = path.join(base, slug, "files", `${slug}-latin-${w}-normal.woff2`);
    const b64 = fs.readFileSync(f).toString("base64");
    css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${w};font-display:swap;`
      + `src:url(data:font/woff2;base64,${b64}) format('woff2');}\n`;
    count++;
  });
});
fs.writeFileSync(out, css);
console.log("[embed-font] wrote app/fonts-embedded.css (" + Math.round(css.length / 1024) + " KB, " + count + " faces)");
