// Embed Manrope (latin subset) as base64 @font-face so the brand font works with
// ZERO external requests — required for offline file:// (assetPrefix "." breaks
// @fontsource's relative url()s). Regenerable; run at prebuild.
const fs = require("fs");
const path = require("path");
const dir = path.resolve(__dirname, "..", "node_modules", "@fontsource", "manrope", "files");
const out = path.resolve(__dirname, "..", "app", "manrope-embedded.css");
const weights = [400, 500, 600, 700, 800];
let css = "/* Auto-generated by scripts/embed-font.js — Manrope latin, base64. Do not edit. */\n";
weights.forEach((w) => {
  const f = path.join(dir, `manrope-latin-${w}-normal.woff2`);
  const b64 = fs.readFileSync(f).toString("base64");
  css += `@font-face{font-family:'Manrope';font-style:normal;font-weight:${w};font-display:swap;`
    + `src:url(data:font/woff2;base64,${b64}) format('woff2');}\n`;
});
fs.writeFileSync(out, css);
console.log("[embed-font] wrote app/manrope-embedded.css (" + Math.round(css.length / 1024) + " KB, " + weights.length + " weights)");
