#!/usr/bin/env python3
"""One-off patch: Phase 7 (XB-14) GILTI/NCTI quantification adds new fields
to aggregateUsIncomeResult (cfcNonElectedInclusionUs/cfcElectedPool/
cfcPerEntityTrace) and computeUsTaxCore (gilti962TaxUsd/cfcDetail), plus
rewrites the "cfc" finding's text and (for founder_indian_company /
us_ccorp_indian_sub, the two fixtures with a >50%-owned foreign corp on
file) the businessEntities/reconciliation-row text. None of these are
derivable by re-running archive/engine-frozen/ (it has no GILTI logic at
all) -- generated by running the UPDATED Python DAG itself over each
fixture's real input profile, then merging just the new/changed keys into
the existing golden JSON, leaving every other already-reviewed field
(including other documented DAG-vs-frozen-engine divergences) untouched.
Same precedent as the otherOrdinaryIncomeUs patch earlier this session.

Run: python3 dag_py/tools/patch_golden_cfc.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "dag_py" / "src"))

from wising_dag.analyze import analyze  # noqa: E402

PROFILES_DIR = REPO_ROOT / "dag_py" / "tests" / "fixtures" / "profiles"
GOLDEN_DIR = REPO_ROOT / "dag_py" / "tests" / "fixtures" / "golden" / "fixtures"


def patch_one(fixture_id: str) -> None:
    profile = json.loads((PROFILES_DIR / f"{fixture_id}.json").read_text())
    golden_path = GOLDEN_DIR / f"{fixture_id}.json"
    golden = json.loads(golden_path.read_text())

    result = analyze({
        "router": profile["router"], "india": profile["india"], "us": profile["us"],
        "monitorAsOf": golden["monitoring"]["asOf"],
    })

    # 1. model.income.us: the 3 new aggregateUsIncomeResult keys.
    us_income = golden["model"]["income"]["us"]
    for k in ("cfcNonElectedInclusionUs", "cfcElectedPool", "cfcPerEntityTrace"):
        us_income[k] = result["model"]["income"]["us"][k]

    # 2. computed.usTax: gilti962TaxUsd/cfcDetail, ONLY on the individual
    # path (computeUsTaxCore) -- entity (usEntityTaxResult) and NRA
    # (computeNraTax) routing never touch these fields, matching the JS
    # run-ustax-full.js carve-out precedent.
    real_us_tax = result["computed"]["usTax"]
    if "gilti962TaxUsd" in real_us_tax:
        golden["computed"]["usTax"]["gilti962TaxUsd"] = real_us_tax["gilti962TaxUsd"]
        golden["computed"]["usTax"]["cfcDetail"] = real_us_tax["cfcDetail"]

    # 3. findings[cfc]: full replace with the new text (rewritten
    # unconditionally whenever it fires -- real numbers once financial data
    # is entered, improved wording even at $0).
    new_findings_by_id = {f["id"]: f for f in result["findings"]}
    for f in golden["findings"]:
        if f["id"] == "cfc" and "cfc" in new_findings_by_id:
            f.update(new_findings_by_id["cfc"])

    # 4. model.assets.businessEntities: "gilti" always updates for any cfc:
    # true row (the by-name dedup merge in _business_entities_result always
    # refreshes this field regardless of which entry -- PGBP or CFC --
    # inserted first). returnForm/calcTrace/incomeUsd only update when this
    # row's OWN calcTrace is genuinely the legacy GILTI text -- when a PGBP
    # business entry shares the same name and was inserted first (e.g.
    # us_ccorp_indian_sub's "Cloudspire India Pvt Ltd", present as BOTH a
    # business_entries[] row and a foreign_corporations[] row), the merge
    # keeps the PGBP entry's own calcTrace/incomeUsd untouched -- overwriting
    # those here would silently swap in the wrong (CFC-only) trace.
    new_be_by_name = {e.get("name"): e for e in result["model"]["assets"]["businessEntities"] if e.get("cfc")}
    for e in golden["model"]["assets"]["businessEntities"]:
        if e.get("cfc") and e.get("name") in new_be_by_name:
            new_e = new_be_by_name[e["name"]]
            e["gilti"] = new_e["gilti"]
            old_detail = (e.get("calcTrace") or {}).get("detail", "")
            if "GILTI inclusion as entered on Layer 1 US for this CFC" in old_detail:
                e["returnForm"] = new_e["returnForm"]
                e["calcTrace"] = new_e["calcTrace"]
                e["incomeUsd"] = new_e["incomeUsd"]

    # 5. computed.reconciliation.rows: the CFC business row's note/usRule
    # text -- unconditionally reworded whenever it fires.
    new_rows_by_head = {r["head"]: r for r in result["computed"]["reconciliation"]["rows"]}
    for r in golden["computed"]["reconciliation"]["rows"]:
        if r["head"] == "business" and "business" in new_rows_by_head and "CFC/NCTI" in new_rows_by_head["business"].get("note", ""):
            r["note"] = new_rows_by_head["business"]["note"]
            r["usRule"] = new_rows_by_head["business"]["usRule"]

    # ensure_ascii left at its default (True) to match the existing files'
    # own serialization convention exactly -- keeps the diff scoped to the
    # actual field changes instead of re-escaping every unicode char in the
    # file (em-dashes, section signs, arrows) that a mismatched ensure_ascii
    # setting would otherwise touch.
    golden_path.write_text(json.dumps(golden, indent=2) + "\n")
    print(f"patched {fixture_id}.json")


def main() -> None:
    ids = [p.stem for p in sorted(PROFILES_DIR.glob("*.json"))]
    for fid in ids:
        patch_one(fid)
    print(f"\n{len(ids)} golden fixtures patched.")


if __name__ == "__main__":
    main()
